#!/bin/sh
set -e

# when no arguments was given
if [ $# -eq 0 ]; then
    echo "Usage: $0 <host>"
    exit 1
fi

# since we can't pass directly argument to slirp binary, we use a wrapper script
# that gets parameters from environment
export DOCKER_HOST_IP="$1"

WORKDIR="$(pwd)"

# will be mounted inside UML as /var/lib/docker
DOCKER_STORAGE="${HOME}/docker_storage"
mkdir -p $DOCKER_STORAGE

$WORKDIR/linux quiet mem=2G rootfstype=hostfs rw \
    eth0=slirp,,"${WORKDIR}/slirp" \
    init="${WORKDIR}/init" \
    WORKDIR="$WORKDIR" \
    HOME="$HOME" \
    DOCKER_STORAGE="$DOCKER_STORAGE" \
